### ISSUE TITLE
Figure out and possibly fix the cause of the robot turning when it tries to move back

### ISSUE THREAD

**Issue by lucky962** [lucky962/RoboCup-Soccer-Amaizeing#9]

**Comment by runningOutOfUsernameIdeas** [comment]
It might be due to the weight of the robot on the different wheels but I still don't exactly know the reason. This effect is also reduced significantly when the robot is at high battery, where it is almost not noticeable.

**Comment by runningOutOfUsernameIdeas** [comment]
I believe I have fixed the problem with a small structural change that makes the L that connects the Motor axle to the wheel axle substantially more rigid. This behavior has yet to be observed after this change
